name: Generate 3D Contribution Graph
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D Contribution Graph
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          OUTPUT_DIR: output/profile-3d-contrib
      - name: Commit & Push
        run: |
          mkdir -p output/profile-3d-contrib
          if [ -d profile-3d-contrib ]; then
            mv profile-3d-contrib output/profile-3d-contrib
          fi
          git config user.name "kosnakam"
          git config user.email "kosnakam@outlook.jp"
          git add output/profile-3d-contrib/
          git diff --cached --quiet && exit 0
          git commit -m "chore: update 3d contribution graph"
          git push
